### ISSUE TITLE
Refactor config code to handle config errors gracefully

### ISSUE THREAD

**Issue by davidscholberg** [dvdmuckle/goify#8]
Error checking in the config-handling code needs to be updated to fail gracefully. See #7 as an example.

**Comment by davidscholberg** [comment]
https://github.com/dvdmuckle/goify/blob/4ad9a78501db06e9ac93f2788235448a8f427a37/cmd/root.go#L102

@dvdmuckle can you elaborate on what the `auth` config variable is and how it's used?

**Comment by dvdmuckle** [comment]
`auth` config variable stores the OAuth2 token as a string of formatted JSON, hence this line of code to unmarshal the JSON into an actual token variable under the global `config` variable.

**Comment by dvdmuckle** [comment]
The `switch` subcommand PR has work on this as I realized this was broken while testing that.
